### PR TITLE
ci: add travis-ci integration

### PR DESCRIPTION
**Pull request by gjnoonan**
Start the CI journey for the project. We will check that monky will compile
under emacs 24.4,25.1,25.2,25.3,26.1 and master

I plan on contributing some big refactorings and new features, so this will
hopefully give us some confidence :-)

### CODE REVIEW

**Comment by ananthakumaran** [comment]
@Bounga just activated travis for this repo.

**Comment by Bounga** [comment]
That’s really great. Thank you guys. Seems like this project is reviving. Gonna have a look to this PR. Thanks.

**Comment by gjnoonan** [comment]
@Bounga yep hopefully we can revive the project. I really like magit and use it daily, having the same kind of interface/functionality  for mercurial (which I still use for personal projects and some clients) will be really nice.

**Comment by Bounga** [comment]
@ananthakumaran Thanks for the activation of Travis.

**Pull request merged**
