### PR TITLE
Fix #45 Add date to log

### LINKED ISSUE #45: Add commit date to hg log

### PR DESCRIPTION
**Pull request by lbolla**

### CODE REVIEW

**Comment by juszczakn** [comment]
I've done something similar on my branch [here](https://github.com/juszczakn/monky/tree/mods), along with some other improvements. If you're interested, I'd enjoy feedback if you check it out.

**Comment by lbolla** [comment]
Any chance to merge this PR?

**Comment by ananthakumaran** [comment]
Sorry, I don't use hg nowadays, so not much incentive and time to manage this plugin. I could add you as a collaborator if you are interested.

**Comment by lbolla** [comment]
@ananthakumaran Sure, I'd be happy to move monky forward.
I use git 90% of my time and monky makes using hg more pleasurable when I have to use it.

**Comment by ananthakumaran** [comment]
Thanks. added

**Comment by juszczakn** [comment]
Just wondering, have you taken a look at [my branch?](https://github.com/juszczakn/monky/tree/mods).
It has a similar change to this, along with some other niceties like bug fixes, names for committers, bookmark hotkeys, and maybe some others. 

Example picture: https://imgur.com/a/kQQde

**Comment by lbolla** [comment]
@juszczakn Is your branch in a "mergeable" state? Can you issue a PR to review your patches?

**Comment by juszczakn** [comment]
@lbolla I think it is, I'll send a PR. It might be a bit hacky.

**Pull request merged**
