### PR TITLE
Fix lexical-binding and namespace

### PR DESCRIPTION
**Pull request by Wilfred**
Add lexical binding, and fix a variable without a namespace.

### CODE REVIEW

**Comment by Wilfred** [comment]
@Bounga thank you :)

If you're happy with me just committing small changes directly to master, I'm happy to do that. Let me know what you prefer.

**Comment by Bounga** [comment]
You're welcome. Sorry but I'm not admin on this repo I have commit rights only.

**Comment by Wilfred** [comment]
@Bounga sorry, I was unclear. Now I have commit access, I can make changes directly without creating pull requests. Are you happy me committing changes directly to master?

**Comment by Bounga** [comment]
@Wilfred oh sorry! If it's a small change that can be made in one small atomic commit and that this change is relevant to all users then yes go ahead. If it's a larger feature then I think that it's better to create a PR so it can be discussed, reviewed and it makes the git history cleaner thanks to the dedicated branch that will eventually be merged.

You've been very prolific lately and your work clearly makes Monky a better package so I think you can legitimately push things by yourself when it makes sense 😉.

**Pull request merged**
